version: "3.8"

services:
  llmdataparser:
    build: .
    environment:
      - GRADIO_SERVER_PORT=7860
    volumes:
      - .:/app
      - huggingface_cache:/app/.cache/huggingface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:7860"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - internal

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - llmdataparser
    networks:
      - internal

networks:
  internal:

volumes:
  huggingface_cache:
