name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

      - name: Run tests
        run: poetry run pytest
